---
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - 2.1.3
addons:
  code_climate:
    repo_token: 38686058eed480dd0fcf8bce9015733e0bae88e44e30f4a1ac63df8aec2f86d8
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
script:
  - echo "Run specs for Knapsack gem"
  - bundle exec rspec spec

  - echo "Generate knapsack report"
  - KNAPSACK_GENERATE_REPORT=true bundle exec rspec --default-path spec_examples --tag focus

  - echo "Run specs with enabled time offset warning"
  - bundle exec rspec --default-path spec_examples

  - echo "Run rake task for the first CI node"
  - CI_NODE_TOTAL=2 CI_NODE_INDEX=0 KNAPSACK_SPEC_PATTERN="spec_examples/**/*_spec.rb" bundle exec rake knapsack:rspec
  - echo "Run rake task for the second CI node"
  - CI_NODE_TOTAL=2 CI_NODE_INDEX=1 KNAPSACK_SPEC_PATTERN="spec_examples/**/*_spec.rb" bundle exec rake knapsack:rspec

  - echo "Check passing arguments to rspec. Run only specs with custom_focus tag"
  - KNAPSACK_SPEC_PATTERN="spec_examples/**/*_spec.rb" bundle exec rake "knapsack:rspec[--tag custom_focus]"

  - echo "Run specs with custom knapsack logger"
  - CUSTOM_LOGGER=true KNAPSACK_SPEC_PATTERN="spec_examples/**/*_spec.rb" bundle exec rake knapsack:rspec

  - echo "Run specs for custom knapsack report path"
  - cp knapsack_report.json custom_knapsack_report.json
  - KNAPSACK_REPORT_PATH="custom_knapsack_report.json" KNAPSACK_SPEC_PATTERN="spec_examples/**/*_spec.rb" bundle exec rake knapsack:rspec

  - echo "Run specs when spec file was removed and still exists in knapsack report json"
  - rm spec_examples/fast/1_spec.rb
  - KNAPSACK_SPEC_PATTERN="spec_examples/**/*_spec.rb" bundle exec rake knapsack:rspec
notifications:
  email: false
